/*
Copyright (c) 2023 Robin E. R. Davies

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/


#include "ToobLooperFourInfo.hpp"
#include "lv2c_ui/Lv2UI.hpp"

using namespace lv2c::ui;
using namespace lv2c;
using namespace record_plugin;


// The plugin info generated by generate_lv2c_plugin_info.

#define LOGO_SVG "CabIRLogo.svg"

// class declaration.
class ToobLooperFourUiPlugin: public Lv2UI {
public:
    using super=Lv2UI;
    ToobLooperFourUiPlugin();
};

ToobLooperFourUiPlugin::ToobLooperFourUiPlugin() 
: super(
    ToobLooperFourUiBase::Create(),
    Lv2cSize(383,729)
    )
{
    Lv2cTheme::ptr theme = Lv2cTheme::Create(true); // start with dark theme.
    theme->paper = Lv2cColor("#081808"); // something dark.
    this->Theme(theme);

}


// Make the plugin visible to LV2 hosts.

REGISTRATION_DECLARATION Lv2UIRegistration<ToobLooperFourUiPlugin> 
toobLooperFourUiRegistration { ToobLooperFourUiBase::UI_URI  };

