/*
Copyright (c) 2023 Robin E. R. Davies

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

#include "lv2c_ui/Lv2UI.hpp"
#include "ToobUi.hpp"

using namespace lv2c::ui;
using namespace lv2c;
using namespace toob;

// The plugin info generated by generate_lv2c_plugin_info.
#include "Toob3BandEqInfo.hpp"

#define PLUGIN_CLASS Toob3BandEqUI
#define PLUGIN_UI_URI_MONO "http://two-play.com/plugins/toob-three-band-eq-ui"
#define PLUGIN_UI_URI_STEREO "http://two-play.com/plugins/toob-three-band-eq-ui-stereo"
#define PLUGIN_INFO_CLASS Toob3BandEqPluginInfo


// class declaration.
class PLUGIN_CLASS: public ToobUi {
public:
    using super=ToobUi;
    using self=PLUGIN_CLASS;
    PLUGIN_CLASS();
};


PLUGIN_CLASS::PLUGIN_CLASS() 
: super(
    PLUGIN_INFO_CLASS::Create(),
    Lv2cSize(731,238), // default window size.
    Lv2cSize(470,200),
    "ToobToob3BandEqLogo.svg"
    )
{
 
}

// Make the plugin visible to LV2 hosts.

int linkToob3BandEqUi = 0; // link target to include the .o file in the final .so.
static REGISTRATION_DECLARATION Lv2UIRegistration<PLUGIN_CLASS> 
registrationMono { PLUGIN_UI_URI_MONO};


static REGISTRATION_DECLARATION Lv2UIRegistration<PLUGIN_CLASS> 
registrationStereo { PLUGIN_UI_URI_STEREO};
