/*
Copyright (c) 2023 Robin E. R. Davies

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

#include "lvtk_ui/Lv2UI.hpp"
#include "lvtk/LvtkVerticalStackElement.hpp"
#include "lvtk/LvtkFlexGridElement.hpp"
#include "lvtk/LvtkSvgElement.hpp"
#include "lvtk/LvtkButtonElement.hpp"

using namespace lvtk::ui;
using namespace lvtk;

// The plugin info generated by generate_lvtk_plugin_info.
#include "ToobChorusInfo.hpp"

#define PLUGIN_CLASS ToobChorusPluginUi
#define PLUGIN_UI_URI "http://two-play.com/plugins/toob-chorus-ui"
#define PLUGIN_INFO_CLASS ToobChorusPluginInfo


 
// class declaration.
class PLUGIN_CLASS: public Lv2UI {
public:
    using super=Lv2UI;
    using self=PLUGIN_CLASS;
    PLUGIN_CLASS();
protected:
    virtual LvtkContainerElement::ptr Render() override;
private:
    void OnHelpClicked();
};


PLUGIN_CLASS::PLUGIN_CLASS() 
: super(
    PLUGIN_INFO_CLASS::Create(),
    LvtkSize(320,200) // default window size.
    )
{

}

void PLUGIN_CLASS::OnHelpClicked()
{
    
}



LvtkContainerElement::ptr PLUGIN_CLASS::Render() {
    auto container = LvtkVerticalStackElement::Create();
    container->Style()
        .VerticalAlignment(LvtkAlignment::Stretch)
        .HorizontalAlignment(LvtkAlignment::Stretch)
        .Background(Theme()->paper);
    {
        LvtkContainerElement::ptr controlContainer = LvtkContainerElement::Create();
        controlContainer->Style()
            .HorizontalAlignment(LvtkAlignment::Stretch)
            .VerticalAlignment(LvtkAlignment::Stretch)
            ;
        {
            auto controls = super::RenderControls();
            controls->Style()
                .FlexJustification(LvtkFlexJustification::Center)
                .VerticalAlignment(LvtkAlignment::Center)
                ;
            controlContainer->AddChild(controls);
        }
        container->AddChild(controlContainer);
    }
    {
        auto bottomBar = LvtkFlexGridElement::Create();
        bottomBar->Style()
            .BorderWidthTop(1)
            .BorderColor(LvtkColor("#E0E0E080"))
            .FlexAlignItems(LvtkAlignment::Center)
            .FlexDirection(LvtkFlexDirection::Row)
            .FlexWrap(LvtkFlexWrap::NoWrap)
            .HorizontalAlignment(LvtkAlignment::Stretch)
            ;
        {
            auto img = LvtkSvgElement::Create();
            img->Source("ToobChorusLogo.svg");
            img->Style()
                .MarginLeft(8)
                .MarginTop(4)
                .MarginBottom(4)
                .Opacity(0.75)
                ;
            bottomBar->AddChild(img);
        }
        {
            auto item = LvtkElement::Create();
            item->Style()
                .HorizontalAlignment(LvtkAlignment::Stretch);
            bottomBar->AddChild(item);
        }
        {
            auto button = LvtkButtonElement::Create();
            button
                ->Variant(LvtkButtonVariant::ImageButton)
                .Icon("help.svg");
            button->Clicked.AddListener(
                [this](const LvtkMouseEventArgs&args)
                {
                    OnHelpClicked();
                    return true;
                }
            );
            bottomBar->AddChild(button);
        }
        container->AddChild(bottomBar);
    }
    return container;


}



// Make the plugin visible to LV2 hosts.

static Lv2UIRegistration<PLUGIN_CLASS> 
registration { PLUGIN_UI_URI};

